[package]
name = "4x8matrix/runtime"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["AsynchronousMatrix"]

description = "A simple package to help load modules in during Roblox runtime."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]

[dev-dependencies]

[dependencies]