[package]
name = "4x8matrix/runtime"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/Roblox-Devs-Dubit/wally-index"
licence = ""
authors = []

description = "A simple package to help load modules in during Roblox runtime."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]

[dev-dependencies]

[dependencies]