# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.

[tools]
luaulsp = "JohnnyMorganz/luau-lsp@1.24.1"
lune = "filiptibell/lune@0.7.11"
selene = "Kampfkarren/selene@0.26.1"