[package]
name = "4x8matrix/console"
version = "2.0.3"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = "MIT"
authors = ["AsynchronousMatrix"]

description = "A Roblox resource to simplify & enhance the Roblox Console/Output"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"
EmoticonReporter = "4x8matrix/emoticon-reporter@1.0.0"

[dependencies]
Signal = "sleitnick/signal@1.5.0"