name: Build Binaries

on:
  workflow_dispatch:

  push:
    branches:
      - Master

permissions:
  contents: write

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Update Binaries
        run: lune update-binaries

      - name: Commit changes
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git add .
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Auto-update package 'Binaries'" && git push || echo "No changes to commit"
