on:
  workflow_dispatch:

  push:
    branches:
      - Master

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Dcumentation Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: 4x8Matrix/Package-Index-Site
          event-type: update-documentation
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Update Binaries
        run: lune update-binaries

      - name: Commit changes
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git add .
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Auto-update documentation '${{ github.event.client_payload.sha }}'" && git push || echo "No changes to commit"
