on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
      - development
      - "release/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Run Linter
        run: lune lint-check

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Run Linter
        run: lune type-check
